name: ostello
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. 
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 200
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 300
        - asset: assets/fonts/Avenir-Regular.ttf
          weight: 400
        - asset: assets/fonts/Avenir-Black.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 800
    

